"""initial schema

Revision ID: 5225ada06165
Revises: 
Create Date: 2026-06-26 22:30:48.866974
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '5225ada06165'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eval_cases',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('expected_files_json', sa.JSON(), nullable=True),
    sa.Column('expected_symbols_json', sa.JSON(), nullable=True),
    sa.Column('expect_refusal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('eval_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('metrics_json', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repos',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('commit_sha', sa.String(length=64), nullable=True),
    sa.Column('file_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ingested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('repo_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_repo_id'), 'chat_sessions', ['repo_id'], unique=False)
    op.create_table('files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('repo_id', sa.String(length=32), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('lang', sa.String(length=32), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id', 'path', name='uq_files_repo_path')
    )
    op.create_index(op.f('ix_files_repo_id'), 'files', ['repo_id'], unique=False)
    op.create_table('ingest_jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('repo_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('phase', sa.String(length=32), nullable=False),
    sa.Column('files_done', sa.Integer(), nullable=False),
    sa.Column('chunks_done', sa.Integer(), nullable=False),
    sa.Column('pct', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingest_jobs_repo_id'), 'ingest_jobs', ['repo_id'], unique=False)
    op.create_table('chunks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('file_id', sa.String(length=32), nullable=False),
    sa.Column('repo_id', sa.String(length=32), nullable=False),
    sa.Column('symbol', sa.String(length=255), nullable=True),
    sa.Column('kind', sa.String(length=64), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('qdrant_point_id', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['repo_id'], ['repos.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_file_id'), 'chunks', ['file_id'], unique=False)
    op.create_index(op.f('ix_chunks_qdrant_point_id'), 'chunks', ['qdrant_point_id'], unique=False)
    op.create_index(op.f('ix_chunks_repo_id'), 'chunks', ['repo_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('citations_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_session_id'), 'messages', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_session_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_chunks_repo_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_qdrant_point_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_file_id'), table_name='chunks')
    op.drop_table('chunks')
    op.drop_index(op.f('ix_ingest_jobs_repo_id'), table_name='ingest_jobs')
    op.drop_table('ingest_jobs')
    op.drop_index(op.f('ix_files_repo_id'), table_name='files')
    op.drop_table('files')
    op.drop_index(op.f('ix_chat_sessions_repo_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_table('repos')
    op.drop_table('eval_runs')
    op.drop_table('eval_cases')
    # ### end Alembic commands ###
